### PR TITLE
fix(Post): new actions button bar structure and changes in styles

### LINKED ISSUE #550: [Bug]: Mobile: new post and reply modal action buttons don't always fit
### Describe the bug

When the New Post or Reply modal is displayed, not all the buttons fit on some device displays.

### Reproduce

1. On mobile that is affected (see screenshots)
2. Find a post in the feed to reply to
3. Click the Reply button
4. Observe emoji button is cropped off to the left

### Screenshots / Recording

**Good**
iPhone 14 Pro Max
Image

**Bad**

iPhone SE

Image

iPhone 12 Pro

Image

### Web Browser

_No response_

### Pubky App Version

8c58e2f86b962edca703e43043b32132df59d513

### Console log output

```shell

```

### PR DESCRIPTION
**Pull request by Nirzhuk**
- Adjusted the padding for the small size variant of the Button component from 'has-[>svg]:px-2.5' to 'has-[>svg]:px-3.5' to ensure consistent spacing.
- Updated related snapshots to reflect the changes in button styles across various components that utilize the Button component.

Designs:

- Desktop -> https://www.figma.com/design/01ZvjSPZnKTNmaEWz0yJsq/shadcn_ui-PUBKY?node-id=20869-130075&m=dev

- Phone -> https://www.figma.com/design/01ZvjSPZnKTNmaEWz0yJsq/shadcn_ui-PUBKY?node-id=20899-171129&m=dev

fix #550

### CODE REVIEW

**Comment by Taewa** [comment]
@greptile-apps
Review again please.

**Comment by Taewa** [comment]
@Nirzhuk 
There is duplicated text limit UI

## [Figma](https://www.figma.com/design/01ZvjSPZnKTNmaEWz0yJsq/shadcn_ui-PUBKY?node-id=20869-130075&m=dev)
image

## Actual
Screenshot 2026-03-26 at 09 01 38

**Comment by Taewa** [comment]
@Nirzhuk 
Also the "Post" icon and "Reply" icon are different on the button. 
Could it be updated in this PR? Or in another PR?

**Review by Taewa — CHANGES_REQUESTED** [review]
I left some comments to update UI

**Comment by Nirzhuk** [comment]
@Taewa fixed

**Comment by Taewa** [comment]
LGTM
Tested mobile & desktop version post + reply buttons

**Review by Taewa — APPROVED** [review]

File: src/components/organisms/PostMain/PostMain.tsx [hunk 1]
```diff
@@ -143,7 +143,7 @@ export function PostMain({
                         onTagClick={() => setTagsExpanded((prev) => !prev)}
                         onReplyClick={handleReplyClick}
                         onRepostClick={handleRepostClick}
-                        className="shrink-0 justify-start md:justify-end"
+                        className="w-full shrink-0 justify-start overflow-y-scroll sm:w-auto md:justify-end"
```
Comment (secondl1ght) [inline src/components/organisms/PostMain/PostMain.tsx:146]: Why was Y scroll overflow added here? This is causing all of the action bars to appear with scrollbars now.

Image
