### PR TITLE
fix(ui): update Hot page styling to match Figma design

### LINKED ISSUE #851: [UI]: Hot page header and styling
### Bug Description

Image

Copy for ‘3 posts’ is too large
Heading should be ‘Hot tags’
Don’t use a second heading above rest of the tags, top 3 tags is just shown in bigger format, then continue with number 4.
Shadows below user pics are missing

### Steps to Reproduce

1. Go to `/hot`

### Affected Area

Tags

### Suspected Layer (if known)

UI / Component (visual issue)

### Frequency

Always (100%)

### Expected Behavior

Compare `/hot` page with design

### Screenshots / Recording

_No response_

### Console Log Output

```shell

```

### Browser & Version

_No response_

### Device

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by Orlandohub**
Fix #851 
- Change heading from "Trending" to "Hot tags" in HotTagsCardsSection
- Fix post count font size to use text-base (16px) in HotTagCard
- Remove duplicate "Hot tags" heading from HotTagsOverview
- Skip first 3 tags in overview (already shown in featured cards)
- Update avatar shadow from shadow-sm to shadow-xs-dark for visibility
- Add border to overflow indicator in AvatarGroup

### CODE REVIEW

File: src/components/organisms/HotTagsOverview/HotTagsOverview.tsx [hunk 1]
```diff
@@ -9,42 +10,48 @@ import { APP_ROUTES } from '@/app/routes';
 import type { HotTagsOverviewProps } from './HotTagsOverview.types';
 
 const DEFAULT_TAGS_LIMIT = 50;
+// Skip first 3 tags as they're shown in featured cards (HotTagsCardsSection)
+const FEATURED_TAGS_OFFSET = 3;
```
Comment (infin1t3) [inline src/components/organisms/HotTagsOverview/HotTagsOverview.tsx]: Consider importing and using `TOP_TAGS_DISPLAY` from `HotTagsCardsSection.constants` here. Both values must stay in sync (currently both are 3), so sharing the constant makes this relationship explicit.
