### PR TITLE
fix(#1187) - UI mobile home feed page design differences

### LINKED ISSUE #781: [Bug]: Mobile: current page indicator in footer is too subtle
### Bug Description

On mobile, the footer buttons are also indicators for current page. The colours used are too subtle. Compared with the design, which uses a stronger grey.

### Steps to Reproduce

1. On mobile, tap on Hot page button in the footer
2. Observe the colour of the Hot button is barely distinguishable from the other buttons

### Affected Area

Navigation / Routing

### Suspected Layer (if known)

UI / Component (visual issue)

### Frequency

Always (100%)

### Expected Behavior

Make the current page's button match the stronger grey used in the design.

### Screenshots / Recording

**Design**

Image

**Actual**

Image

https://github.com/user-attachments/assets/bd05ad97-4ee9-4755-aa87-4d47e5a9c673

### Console Log Output

```shell

```

### Browser & Version

_No response_

### Device

_No response_

### Additional Context

_No response_

### LINKED ISSUE #1187: [UI]: Mobile: Home (feed) page design differences
After signing in, on the home page the feed is displayed.
There are multiple differences between current implementation and the design.

1. Too little vertical spacing between Pubky logo and new post input area
2. Too much vertical spacing between new post input's placeholder text and the bottom of the container
3. Too much vertical spacing in a repost between username (and their truncated pubky) and the embedded post
4. Check vertical alignment with menu button in top left for: new post container and first post in tree
5. Appearance of footer buttons is different from design, please fix bg color, blur effect, outline + add selected state for selected page (https://github.com/pubky/pubky-app/issues/781)

Image

### PR DESCRIPTION
**Pull request by Nirzhuk**
Fix https://github.com/pubky/pubky-app/issues/1187
fix https://github.com/pubky/pubky-app/issues/781

### CODE REVIEW

File: src/components/organisms/PostContent/PostContent.tsx
Comment (infin1t3) [inline src/components/organisms/PostContent/PostContent.tsx:10]: The JSDoc comment and the inline comment on line 29 still describe PostContentBase as "always rendered" and as a "structural wrapper," but after this PR, PostContentBase returns null for plain reposts with no attachments.

Update the doc with:
```
/**
 * PostContent - Renders post content with repost preview support.
 *
 * **Rendering logic:**
 * - **Regular post**: Renders PostContentBase (text, embeds, attachments)
 * - **Repost with content (quote)**: Renders PostContentBase (quote text) + PostPreviewCard (original post)
 * - **Repost without content (plain repost)**: PostContentBase returns null + PostPreviewCard (original post)
 */
```

**Comment by catch-21** [comment]
@Nirzhuk https://github.com/pubky/pubky-app/issues/781 is probably a duplicate of https://github.com/pubky/pubky-app/issues/301 and already addressed in https://github.com/pubky/pubky-app/pull/1609. My bad. Would you mind reverting your change in https://github.com/pubky/pubky-app/pull/1607?

**Review by infin1t3 — CHANGES_REQUESTED** [review]
https://github.com/user-attachments/assets/ecb14cef-fe87-40dd-897f-4f7629e1573f

Extra spacing in the Header, not enough spacing in post (4 vs 6) - check video for more details

I stopped reviewing at that point - consult Figma design for that screen and implement correct spacings - https://www.figma.com/design/01ZvjSPZnKTNmaEWz0yJsq/shadcn_ui-PUBKY?node-id=21607-104424&m=dev

Also make sure everything else is based on the spec.

**Comment by Nirzhuk** [comment]
@vlada Video of the fix. Decided to take a different approach and clean everything in code wise

https://github.com/user-attachments/assets/3bd8f3bf-1fb1-4d78-b029-65c594dc7665



The only page is not working is when we signing because this bug.
https://github.com/pubky/pubky-app/issues/1631

File: src/components/organisms/PostContent/PostContent.tsx [hunk 1]
```diff
@@ -36,7 +28,7 @@ export function PostContent({ postId, className }: PostContentOrganismProps) {
 
       {/* Show original post preview for reposts */}
       {shouldRenderRepostPreview && (
-        <Molecules.PostPreviewCard postId={originalPostId} className={Libs.cn('bg-muted', hasContent && 'mt-4')} />
+        <Molecules.PostPreviewCard postId={originalPostId} className={Libs.cn('bg-muted')} />
```
Comment (infin1t3) [inline src/components/organisms/PostContent/PostContent.tsx]: `Libs.cn` is obsolete now.

**Review by infin1t3 — CHANGES_REQUESTED** [review]

**Comment by infin1t3** [comment]
@greptileai review

**Review by infin1t3 — APPROVED** [review]
https://github.com/user-attachments/assets/97056a51-b7eb-4d14-96a8-727c17efa072



Tested at `c1e1514b129c982e0714bcd7b517c452192b86d0` - LGTM

Notes: 
This PR introduces Framer motion dependency which was okayed here
https://synonymworkspace.slack.com/archives/C09HQTLAARF/p1771507197065499



Did a smoke test of changes and everything looks ok.

**Review by secondl1ght — COMMENTED** [review]
FYI this PR introduced a UI regression where the Pubky logo in the mobile header is no longer vertically aligned. It affects multiple routes, the screenshots below were taken on the Settings route:

BEFORE
Image

AFTER
Image
