### PR TITLE
fix(i18n): add internationalization to all toast messages

### LINKED ISSUE #1132: [Bug]: i18n does not cover toast
### Bug Description

Language change does not impact toast messages.

### Steps to Reproduce

1. Change language to non-English
2. Invoked toast (e.g. edit profile)
3. Observe toast is in English

### Affected Area

Notifications

### Suspected Layer (if known)

UI / Component (visual issue)

### Frequency

Always (100%)

### Expected Behavior

Toast has translations

### Screenshots / Recording

Image

### Console Log Output

```shell

```

### Browser & Version

_No response_

### Device

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by MiguelMedeiros**
## Summary

Fixes #1132 - i18n does not cover toast messages

This PR adds internationalization support to all toast messages throughout the application. Previously, many toast notifications were displaying hardcoded English strings regardless of the user's language preference.

### New Translation Keys Added

Added to all 9 locale files (`en`, `pt-BR`, `de`, `fr`, `it`, `es`, `zh`, `ja`, `ar`):

- `toast.status.updateFailed` - Status update failure message
- `toast.fullscreen.error` - Fullscreen enable error
- `toast.logout.failed` - Logout failure message
- `toast.post.attachmentsLoadFailed` - Post attachments load failure

#### Hooks (14 files)
| File | Toast Messages Updated |
|------|----------------------|
| `useProfileForm.tsx` | Profile update success, session expired, save failed, fetch failed |
| `useCopyrightForm.ts` | Success, error sending request |
| `useReportPost.ts` | User not loaded, submit failed |
| `useFeedback.ts` | User not loaded, submit failed |
| `useBookmark.ts` | Login required, added, removed, add/remove failed |
| `usePost.tsx` | Reply posted, post created, post edited, repost success/failed, attachments cleared |
| `useDeletePost.tsx` | Invalid post ID, post deleted, delete failed |
| `useProfileActions.tsx` | Logout failed, user not loaded, status update failed |
| `useCopyToClipboard.tsx` | Copy success/failed (with default translations) |
| `usePostInput.ts` | Max files, unsupported type, file too large |
| `usePostArticle.ts` | Parse error, cover image error |
| `usePostTags.tsx` | Already using translations (verified) |
| `useTagged.tsx` | Already using translations (verified) |
| `useSignOut.ts` | Already using translations (verified) |

#### Components (3 files)
| File | Toast Messages Updated |
|------|----------------------|
| `PostAttachmentsImagesAndVideos.tsx` | Fullscreen error |
| `NotificationItem.tsx` | Parse article error |
| `PostAttachments.tsx` | Attachments load failed |

#### Preview of a few toasts

https://github.com/user-attachments/assets/9bb340da-ebab-45f0-9560-de21cb79914c

### Pre-requisites
- [ ] Switch language to non-English (e.g., Portuguese, German, Spanish)

### Profile Actions
- [ ] Edit profile and save → Verify "Profile updated" toast is translated
- [ ] Edit profile with expired session → Verify "Session expired" toast is translated
- [ ] Attempt to update status → Verify success/error toasts are translated

### Post Actions
- [ ] Create a new post → Verify "Post created" toast is translated
- [ ] Reply to a post → Verify "Reply posted" toast is translated
- [ ] Edit a post → Verify "Post edited" toast is translated
- [ ] Delete a post → Verify "Post deleted" toast is translated
- [ ] Repost a post → Verify "Reposted!" toast is translated

### Bookmark Actions
- [ ] Add a bookmark → Verify "Bookmark added" toast is translated
- [ ] Remove a bookmark → Verify "Bookmark removed" toast is translated
- [ ] Try to bookmark while logged out → Verify login required toast is translated

### File/Attachment Actions
- [ ] Try to upload more than max files → Verify error toast is translated
- [ ] Try to upload unsupported file type → Verify error toast is translated
- [ ] Try to upload file exceeding max size → Verify error toast is translated
- [ ] Switch post to article mode with attachments → Verify "Attachments cleared" toast is translated

### Copy Actions
- [ ] Copy pubky to clipboard → Verify success toast is translated
- [ ] Copy link to clipboard → Verify success toast is translated

### Tag Actions
- [ ] Add a tag to a post → Verify "Tag added" toast is translated
- [ ] Remove a tag from a post → Verify "Tag removed" toast is translated

### Feedback/Report Actions
- [ ] Submit feedback → Verify success/error toasts are translated
- [ ] Report a post → Verify success/error toasts are translated

### Copyright Form
- [ ] Submit copyright request → Verify success/error toasts are translated

### Media Actions
- [ ] Open image in fullscreen (if supported) and trigger error → Verify error toast is translated

### Auth Actions
- [ ] Sign out → Verify any error toasts are translated

### Article View
- [ ] View a malformed article → Verify parse error toast is translated
- [ ] View article with missing cover image → Verify error toast is translated

### CODE REVIEW

File: src/hooks/useProfileActions/useProfileActions.tsx [hunk 1]
```diff
@@ -56,28 +60,28 @@ export function useProfileActions({ publicKey, link }: UseProfileActionsProps):
...
-  }, [router]);
+  }, [router, tLogout]);
 
   const onStatusChange = useCallback(
     async (status: string) => {
       const currentUserPubky = authStore.currentUserPubky;
       if (!currentUserPubky) {
         Libs.Logger.error('No authenticated user found');
-        Molecules.showErrorToast({ description: 'User profile not loaded. Please try again.' });
+        Molecules.showErrorToast({ description: tReport('userNotLoaded') });
```
[the remark this answers is not in the document]
Comment (MiguelMedeiros) [reply src/hooks/useProfileActions/useProfileActions.tsx]: resolved here: https://github.com/pubky/pubky-app/pull/1592/commits/0b5e7b079ea1d81ca6dcf3939d7196d679cf5cd3

**Comment by MiguelMedeiros** [comment]
@greptile review it again!

File: messages/ja.json
Comment (MiguelMedeiros) [inline messages/ja.json:1]: @Taewa if you can comment on these changes would be nice! :D

Comment (Taewa) [reply messages/ja.json:1]: @MiguelMedeiros 
LGTM, although I am not a native Japanese speaker :)

**Review by Orlandohub — APPROVED** [review]
